services:
  redis:
    image: redis:8.2.1
    container_name: redis_course
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:16
    container_name: postgres_course
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
