spring:
  main:
    banner-mode: off
  application:
    name: course
  datasource:
    url: jdbc:postgresql://localhost:5434/mydatabase
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: 123
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenkhoe2652004@gmail.com
    password: swwdiguqwurzauzi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          sll:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
      enabled: true
  liquibase:
    change-log: classpath:db.changelog/schema.v1_0/db.changelog.xml

server:
  port: 8081

app:
  token:
    expire-seconds: 604800

logging:
  level:
    root: info
  webtech:
    online:
      course: DEBUG

youtube:
  client:
    secrets:
      file: youtubeDriveUpload.json
  credentials:
    folder: credentials

google:
  credentials:
    folder: ggCredentials
  drive:
    folderId: 1mHT6DleGLbKh0-Tvr_iGUzywFQsbbFeF

